---
- name: Install Apache from an MSI 
  hosts: windows 
 
  tasks:
    - name: Create directory structure
      win_file:
        path: C:\temp\
        state: directory
    - name: Download the notepad++ installer
      win_get_url:
        url: 'https://astuteinternet.dl.sourceforge.net/project/notepadmsi/v7.6.6/Notepad%2B%2B7.6.6.msi'
        dest: 'C:\temp\Notepad%2B%2B7.6.6.msi'

    - name: Install exe
      win_package: 
        path: 'C:\temp\Notepad%2B%2B7.6.6.msi'
        state: present
